#!/bin/bash -eux

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

if [ "$USE_VARS_STORE" == true ]; then
  trap commit_vars_store EXIT
fi

function main() {
  echo "====================DEBUG===================="
  ls -al vars-store
  pwd vars-store
  echo "============================================="

  check_input_params
  setup_bosh_env_vars
  if [ "$REGENERATE_VARS_STORE" == true ]; then
    remove_vars_store
  fi
  
  echo "====================DEBUG===================="
  ls -al vars-store
  pwd vars-store
  echo "============================================="
  
  bosh_interpolate
  bosh_deploy
}

main
